training:
  total_steps: 10000000
  batch_size: 32
  learning_rate: 3e-4
  min_lr: 1e-5
  weight_decay: 0.1
  checkpoint_steps: 10000
  val_batch_size: 16
  run_validation: true
  domain_weights:
    c4: 0.7
    wikipedia: 0.2
    math: 0.1